vich_uploader:
    db_driver: orm
    mappings:
        audio_assets:
            uri_prefix:         '%app.path.audio_assets%'
            upload_destination: '%kernel.root_dir%/../web/uploads/audio/'
        episode_images:
            uri_prefix:         '%app.path.episode_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/podcasts/'
        podcast_images:
            uri_prefix:         '%app.path.podcast_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/episodes'

easy_admin:
    site_name: Podlatch Publisher
    design:
        menu:
            - label: 'Podcast'
              icon: 'podcast'
              children:
                  - entity: 'Podcast'
                    label: 'Shows'
                    icon: 'podcast'
                  - { entity: 'PodcastEpisode', label: 'Episodes', icon: 'play', default: true }
            - label: 'Config'
              icon: cogs
              children:
                  - { entity: 'User', icon: 'user'}
            - label: 'About'
              icon: info-circle
              children:
                  #- { label: 'Help', route: 'help_index' }
                  - { label: 'Docs', icon: book, url: 'http://example.com/external-docs' }
                  - { label: '%app.version%' }
    entities:
        Podcast:
            class: Podlatch\PublisherCoreBundle\Entity\PodcastShow
            list:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.podcast_images%' }
                    - title
                    - author
                    - episodes
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Basic information' }
                    - title
                    - author
                    - ownerName
                    - ownerMail
                    - isExplicit
                    - {
                      property: copyright,
                      type: choice,
                      type_options: {
                        choices: {
                            'CC-BY-SA':'CC-BY-SA',
                            'CC-BY-SA-NC':'CC-BY-SA-NC',
                            'CC-BY':'CC-BY',
                            'CC-SA':'CC-SA',
                            'All Rights Reserved':'All Rights Reserved',
                        }
                      }}
                    - {
                        property: category,
                        type: choice,
                        type_options: {
                            choices: {
                                'Arts:Design':'Arts:Design',
                                'Arts:Fashion & Beauty':'Arts:Fashion & Beauty',
                                'Arts:Food':'Arts:Food',
                                'Arts:Literature':'Arts:Literature',
                                'Arts:Performing Arts':'Arts:Performing Arts',
                                'Arts:Visual Arts':'Arts:Visual Arts',
                                'Business:Business News':'Business:Business News',
                                'Business:Careers':'Business:Careers',
                                'Business:Investing':'Business:Investing',
                                'Business:Management & Marketing':'Business:Management & Marketing',
                                'Comedy':'Comedy',
                                'Education:Educational Technology':'Education:Educational Technology',
                                'Education:Higher Education':'Education:Higher Education',
                                'Education:K-12':'Education:K-12',
                                'Education:Language Courses':'Education:Language Courses',
                                'Education:Training':'Education:Training',
                                'Games & Hobbies:Automotive':'Games & Hobbies:Automotive',
                                'Games & Hobbies:Aviation':'Games & Hobbies:Aviation',
                                'Games & Hobbies:Hobbies':'Games & Hobbies:Hobbies',
                                'Games & Hobbies:Other Games':'Games & Hobbies:Other Games',
                                'Games & Hobbies:Video Games':'Games & Hobbies:Video Games',
                                'Government & Organizations:Local':'Government & Organizations:Local',
                                'Government & Organizations:National':'Government & Organizations:National',
                                'Government & Organizations:Non-Profit':'Government & Organizations:Non-Profit',
                                'Government & Organizations:Regional':'Government & Organizations:Regional',
                                'Health:Alternative Health':'Health:Alternative Health',
                                'Health:Fitness & Nutrition':'Health:Fitness & Nutrition',
                                'Health:Self-Help':'Health:Self-Help',
                                'Health:Sexuality':'Health:Sexuality',
                                'Health:Kids & Family':'Health:Kids & Family',
                                'Music':'Music',
                                'Kids & Family':'Kids & Family',
                                'News & Politics':'News & Politics',
                                'Religion & Spirituality:Buddhism':'Religion & Spirituality:Buddhism',
                                'Religion & Spirituality:Christianity':'Religion & Spirituality:Christianity',
                                'Religion & Spirituality:Hinduism':'Religion & Spirituality:Hinduism',
                                'Religion & Spirituality:Islam':'Religion & Spirituality:Islam',
                                'Religion & Spirituality:Judaism':'Religion & Spirituality:Judaism',
                                'Religion & Spirituality:Other':'Religion & Spirituality:Other',
                                'Religion & Spirituality:Spirituality':'Religion & Spirituality:Spirituality',
                                'Science & Medicine:Medicine':'Science & Medicine:Medicine',
                                'Science & Medicine:Natural Sciences':'Science & Medicine:Natural Sciences',
                                'Science & Medicine:Social Sciences':'Science & Medicine:Social Sciences',
                                'Society & Culture:History':'Society & Culture:History',
                                'Society & Culture:Personal Journals':'Society & Culture:Personal Journals',
                                'Society & Culture:Philosophy':'Society & Culture:Philosophy',
                                'Society & Culture:Places & Travel':'Society & Culture:Places & Travel',
                                'Sports & Recreation:Amateur':'Sports & Recreation:Amateur',
                                'Sports & Recreation:College & High School':'Sports & Recreation:College & High School',
                                'Sports & Recreation:Outdoor':'Sports & Recreation:Outdoor',
                                'Sports & Recreation:Professional':'Sports & Recreation:Professional',
                                'Technology:Gadgets':'Technology:Gadgets',
                                'Technology:Podcasting':'Technology:Podcasting',
                                'Technology:Software How-To':'Technology:Software How-To',
                                'Technology:Tech News':'Technology:Tech News',
                                'TV & Film':'TV & Film',
                            }
                        }}
                    - { type: 'group', css_class: 'col-sm-6', label: 'Meta' }
                    - { property: 'slug', type: 'text',type_options: { disabled: true } }
                    - { property: 'description', type: 'textarea' }
                    - { property: 'imageFile', type: 'vich_image' }

        PodcastEpisode:
            class: Podlatch\PublisherCoreBundle\Entity\PodcastEpisode
            list:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.episode_images%' }
                    - title
                    - podcastShow
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-8', label: 'Basic information' }
                    - { property: 'podcastShow', label: 'Podcast',type: 'easyadmin_autocomplete', type_options: { class: 'Podlatch\PublisherCoreBundle\Entity\PodcastShow' } }
                    - title
                    - summary
                    - releasedAt
                    - { property: 'description', type: 'textarea' }
                    - { type: 'group', css_class: 'col-sm-4', label: 'Media' }
                    - { property: 'audioFile', label: 'Audio', help: 'mp3 preferred', type: 'vich_file' }
                    - { property: 'imageFile', label: 'Image', type: 'vich_image', help: '600x600px' }
        User:
            class: Podlatch\PublisherBackendBundle\Entity\User
            list:
                fields:
                    - id
                    - enabled
                    - username
                    - email
                    - lastLogin
                    - roles
            form:
                fields:
                    - username
                    - email
                    - enabled
                    - lastLogin
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
