#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
easy_admin:
  site_name: Podlatch Publisher
  design:
    assets:
      css:
        - 'css/backend.min.css'
      js:
        - 'js/backend.min.js'
    menu:
      - label: 'Podcast'
        icon: 'podcast'
        children:
          - entity: 'Podcast'
            label: 'Shows'
            icon: 'podcast'
          - { entity: 'PodcastEpisode', label: 'Episodes', icon: 'play', default: true }
      - label: 'Config'
        icon: cogs
        children:
          - { entity: 'User', icon: 'user'}
      - label: 'CMS'
        icon: book
        children:
          - { entity: 'Pages', icon: 'book' }
      - label: 'About'
        icon: info-circle
        children:
          #- { label: 'Help', route: 'help_index' }
          - { label: 'Docs', icon: book, url: 'https://podlat.ch' }
          - { label: '%app.version%' }
  entities:
    Project:
      class: App\Entity\PodcastShow
    Podcast:
      class: App\Entity\PodcastShow
      list:
        fields:
          - { property: 'visibleInWebsite',  type: 'toggle' }
          - { property: 'image', type: 'image', base_path: '%app.path.podcast_images%' }
          - title
          - author
          - episodes
      form:
        fields:
          - { type: 'group', css_class: 'col-sm-6', label: 'Basic information' }
          - title
          - subtitle
          - author
          - ownerName
          - ownerMail
          - isExplicit
          - { property: copyright, type: 'choice', type_options: { choices: {'CC-BY-SA': 'CC-BY-SA','CC-BY-SA-NC': 'CC-BY-SA-NC','CC-BY-ND': 'CC-BY-ND','CC-BY': 'CC-BY','CC-SA': 'CC-SA','All-Rights-Reserved': 'All_Rights_Reserved'}}}
          - { property: language, type: 'choice', type_options: { choices: { 'de_DE': 'de_DE', 'en_US': 'en_US',} } }
          - { property: showType,type: 'choice',type_options: {  choices: {    'episodic': 'episodic',    'serial': 'serial'  }}}
          - { property: category,  type: 'choice',  type_options: {    choices: {      'Arts:Design': 'Arts:Design',      'Arts:Fashion & Beauty': 'Arts:Fashion & Beauty',      'Arts:Food': 'Arts:Food',      'Arts:Literature': 'Arts:Literature',      'Arts:Performing Arts': 'Arts:Performing Arts',      'Arts:Visual Arts': 'Arts:Visual Arts',      'Business:Business News': 'Business:Business News',      'Business:Careers': 'Business:Careers',      'Business:Investing': 'Business:Investing',      'Business:Management & Marketing': 'Business:Management & Marketing',      'Comedy': 'Comedy',      'Education:Educational Technology': 'Education:Educational Technology',      'Education:Higher Education': 'Education:Higher Education',      'Education:K-12': 'Education:K-12',      'Education:Language Courses': 'Education:Language Courses',      'Education:Training': 'Education:Training',      'Games & Hobbies:Automotive': 'Games & Hobbies:Automotive',      'Games & Hobbies:Aviation': 'Games & Hobbies:Aviation',      'Games & Hobbies:Hobbies': 'Games & Hobbies:Hobbies',      'Games & Hobbies:Other Games': 'Games & Hobbies:Other Games',      'Games & Hobbies:Video Games': 'Games & Hobbies:Video Games',      'Government & Organizations:Local': 'Government & Organizations:Local',      'Government & Organizations:National': 'Government & Organizations:National',      'Government & Organizations:Non-Profit': 'Government & Organizations:Non-Profit',      'Government & Organizations:Regional': 'Government & Organizations:Regional',      'Health:Alternative Health': 'Health:Alternative Health',      'Health:Fitness & Nutrition': 'Health:Fitness & Nutrition',      'Health:Self-Help': 'Health:Self-Help',      'Health:Sexuality': 'Health:Sexuality',      'Health:Kids & Family': 'Health:Kids & Family',      'Music': 'Music',      'Kids & Family': 'Kids & Family',      'News & Politics': 'News & Politics',      'Religion & Spirituality:Buddhism': 'Religion & Spirituality:Buddhism',      'Religion & Spirituality:Christianity': 'Religion & Spirituality:Christianity',      'Religion & Spirituality:Hinduism': 'Religion & Spirituality:Hinduism',      'Religion & Spirituality:Islam': 'Religion & Spirituality:Islam',      'Religion & Spirituality:Judaism': 'Religion & Spirituality:Judaism',      'Religion & Spirituality:Other': 'Religion & Spirituality:Other',      'Religion & Spirituality:Spirituality': 'Religion & Spirituality:Spirituality',      'Science & Medicine:Medicine': 'Science & Medicine:Medicine',      'Science & Medicine:Natural Sciences': 'Science & Medicine:Natural Sciences',      'Science & Medicine:Social Sciences': 'Science & Medicine:Social Sciences',      'Society & Culture:History': 'Society & Culture:History',      'Society & Culture:Personal Journals': 'Society & Culture:Personal Journals',      'Society & Culture:Philosophy': 'Society & Culture:Philosophy',      'Society & Culture:Places & Travel': 'Society & Culture:Places & Travel',      'Sports & Recreation:Amateur': 'Sports & Recreation:Amateur',      'Sports & Recreation:College & High School': 'Sports & Recreation:College & High School',      'Sports & Recreation:Outdoor': 'Sports & Recreation:Outdoor',      'Sports & Recreation:Professional': 'Sports & Recreation:Professional',      'Technology:Gadgets': 'Technology:Gadgets',      'Technology:Podcasting': 'Technology:Podcasting',      'Technology:Software How-To': 'Technology:Software How-To',      'Technology:Tech News': 'Technology:Tech News',      'TV & Film': 'TV & Film',    }}}
          - { property: 'visibleInWebsite', type: 'checkbox'}
          - { type: 'group', css_class: 'col-sm-6', label: 'Meta' }
          - { property: 'slug', type: 'text',type_options: { disabled: true } }
          - { property: 'description', type: 'textarea' }
          - { property: 'itunesUrl', type: 'text' }
          - { property: 'imageFile', type: 'vich_image' }
          - { property: 'users', type_options: { by_reference: false } }
    PodcastEpisode:
      class: App\Entity\PodcastEpisode
      list:
        fields:
          - { property: 'published',  type: 'toggle' }
          - { property: 'podcastShow', label: 'Podcast'  }
          - { property: 'episodeSeason', label: 'Season'  }
          - { property: 'episodeNumber', label: 'Episode'  }
          - title
          - { property: 'image', type: 'image', base_path: '%app.path.episode_images%' }
      form:
        fields:
          - { type: 'tab' , label: 'General' }
          - { type: 'group', css_class: 'col-sm-8', label: 'Basic information' }
          - { property: 'podcastShow', label: 'Podcast',type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\PodcastShow', required: true  } }
          - episodeSeason
          - episodeNumber
          - title
          - subtitle
          - {property: episodeType,type: 'choice',type_options: {  choices: {    'full':'full',    'trailer':'trailer',    'bonus':'bonus'  }}}
          - summary
          - published
          - releasedAt
          - { property: 'summary', type: 'textarea' }
          - { type: 'group', css_class: 'col-sm-4', label: 'Media' }
          - { property: 'audioFile', label: 'Audio', help: 'mp3 preferred', type: 'vich_file' }
          - { property: 'imageFile', label: 'Image', type: 'vich_image', help: '600x600px' }
          - { type: 'tab' , label: 'Advanced' }

      new:
        fields:
          - '-audioFile'
          - '-imageFile'
          - '-published'
    User:
      class: App\Entity\User

      list:
        fields:
          - id
          - enabled
          - username
          - email
          - lastLogin
          - roles
      form:
        fields:
          - username
          - email
          - enabled
          # if administrators are allowed to edit users' passwords and roles, add this:
          - { property: 'plainPassword', type: 'text', type_options: { required: false } }
          - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
    Pages:
      label: admin.cms.pages
      class: App\Entity\Page
      show:
        fields: [ id, parent, title, slug, tree, content, metaDescription, metaTitle, category, host, locale, homepage, enabled ]
      list:
        fields: [ { property: enabled, type: toggle },id, podcastShow, title, slug ]
      form:
        fields: [ title, slug, content, metaDescription, metaTitle, metaKeywords, css, js, { property: 'podcastShow', label: 'Podcast',type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\PodcastShow', required: true  } }, enabled ]

