publisher_frontend:
    resource: "@PublisherFrontendBundle/Resources/config/routing.yml"
    prefix:   /

podlatch_core:
    resource: "@PublisherCoreBundle/Resources/config/routing.yml"

publisher_backend:
    resource: "@PublisherBackendBundle/Resources/config/routing.yml"
    prefix:   /backend

app:
    resource: '@AppBundle/Controller/'
    type: annotation

easy_admin_bundle:
    resource: "@EasyAdminExtensionBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"