<?php

namespace Podlatch\PublisherBundle\Repository;

/**
 * PodcastEpisodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PodcastShowRepository extends \Doctrine\ORM\EntityRepository
{
}
