#index:
#    path: /
#    controller: App\Controller\DefaultController::index
fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"
  prefix:   /

easy_admin_bundle:
  resource: "../src/Controller/"
  type:     annotation
  prefix:   /admin

publisher_frontend_homepage:
  path:     /
  controller: App\Controller\DefaultController::dashboardAction

publisher_frontend_podcast_overview:
  path:     /{podcastId}
  controller: App\Controller\DefaultController::indexAction

publisher_frontend_podcast_episode_detail:
  path:     /{podcastId}/{episodeId}
  controller: App\Controller\DefaultController::indexAction

publisher_frontend_itunes_feed:
  path:     /feed/mp3/{podcastId}.xml
  controller: App\Controller\DefaultController::feedAction

