vich_uploader:
    db_driver: orm
    mappings:
        audio_assets:
            uri_prefix:         '%app.path.audio_assets%'
            upload_destination: '%kernel.root_dir%/../web/uploads/audio/'

easy_admin:
    entities:
        Podcast:
            class: Podlatch\PublisherBundle\Entity\PodcastShow
        PodcastEpisode:
            class: Podlatch\PublisherBundle\Entity\PodcastEpisode
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Basic information' }
                    - { property: 'podcastShow', label: 'Podcast',type: 'easyadmin_autocomplete', type_options: { class: 'Podlatch\PublisherBundle\Entity\PodcastShow' } }
                    - title
                    - { property: 'description', type: 'textarea' }
                    - summary
                    - { type: 'group', css_class: 'col-sm-6', label: 'Media', help: 'Only for administrators' }
                    - { property: 'audioFile', type: 'vich_file' }
        User:
            class: Podlatch\PublisherBundle\Entity\User
            form:
                fields:
                    - username
                    - email
                    - enabled
                    - lastLogin
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
