vich_uploader:
    db_driver: orm
    mappings:
        audio_assets:
            uri_prefix:         '%app.path.audio_assets%'
            upload_destination: '%kernel.root_dir%/../web/uploads/audio/'
        episode_images:
            uri_prefix:         '%app.path.episode_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/podcasts/'
        podcast_images:
            uri_prefix:         '%app.path.podcast_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/episodes'

easy_admin:
    site_name: Podlatch Publisher
    design:
        menu:
            - label: 'Podcast'
              icon: 'podcast'
              children:
                  - entity: 'Podcast'
                    label: 'Shows'
                    icon: 'podcast'
                  - { entity: 'PodcastEpisode', label: 'Episodes', icon: 'play', default: true }
            - label: 'Config'
              icon: cogs
              children:
                  - { entity: 'User', icon: 'user'}
            - label: 'About'
              icon: info-circle
              children:
                  #- { label: 'Help', route: 'help_index' }
                  - { label: 'Docs', icon: book, url: 'http://example.com/external-docs' }
                  - { label: '%app.version%' }
    entities:
        Podcast:
            class: Podlatch\PublisherBundle\Entity\PodcastShow
            list:
                fields:
                - id
                - { property: 'image', type: 'image', base_path: '%app.path.podcast_images%' }
                - title
                - author
                - episodes

        PodcastEpisode:
            class: Podlatch\PublisherBundle\Entity\PodcastEpisode
            list:
                fields:
                    - id
                    - { property: 'image', type: 'image', base_path: '%app.path.episode_images%' }
                    - title
                    - podcastShow
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Basic information' }
                    - { property: 'podcastShow', label: 'Podcast',type: 'easyadmin_autocomplete', type_options: { class: 'Podlatch\PublisherBundle\Entity\PodcastShow' } }
                    - title
                    - summary
                    - { property: 'description', type: 'textarea' }
                    - { type: 'group', css_class: 'col-sm-6', label: 'Media', help: 'Only for administrators' }
                    - { property: 'audioFile', type: 'vich_file' }
                    - { property: 'imageFile', type: 'vich_image' }
        User:
            class: Podlatch\PublisherBundle\Entity\User
            list:
                fields:
                    - id
                    - enabled
                    - username
                    - email
                    - lastLogin
                    - roles
            form:
                fields:
                    - username
                    - email
                    - enabled
                    - lastLogin
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
